/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package module1gui;
import RelationalDatabase.*;

/**
 *
 * @author ASUS
 */
public class RelationDetailsPage extends javax.swing.JFrame {

    /**
     * Creates new form RelationDetailsPage
     */
    public static Relation R;
    
    public RelationDetailsPage(Relation R) {
        this.R = R;
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RelPageTitleLabel = new javax.swing.JLabel();
        RelationInputLabel = new javax.swing.JLabel();
        FDInputLabel = new javax.swing.JLabel();
        InpFDDisp = new javax.swing.JLabel();
        InpRelDisp = new javax.swing.JLabel();
        TabbedPane = new javax.swing.JTabbedPane();
        RelDetailsPanel = new javax.swing.JPanel();
        CandidateLabel = new javax.swing.JLabel();
        MinCovLabel = new javax.swing.JLabel();
        CandidateKeysLabel = new javax.swing.JLabel();
        MinimalCoverLabel = new javax.swing.JLabel();
        xNFLabel = new javax.swing.JLabel();
        NormalFormLabel = new javax.swing.JLabel();
        FDLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        FDTableDispTextArea = new javax.swing.JTextArea();
        DecomposedTablePanel = new javax.swing.JPanel();
        FinishButton = new javax.swing.JButton();
        DecomposedRelLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        DecomposedRelationTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RELATION AND DECOMPOSITION DETAILS");
        setBounds(new java.awt.Rectangle(100, 50, 0, 0));

        RelPageTitleLabel.setBackground(new java.awt.Color(51, 255, 255));
        RelPageTitleLabel.setFont(new java.awt.Font("Tahoma", 1, 33)); // NOI18N
        RelPageTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RelPageTitleLabel.setText("Relational Database Normalizer (Module 1)");
        RelPageTitleLabel.setOpaque(true);

        RelationInputLabel.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        RelationInputLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        RelationInputLabel.setText("Input Relation :");

        FDInputLabel.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        FDInputLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        FDInputLabel.setText("Input FDs :");

        InpFDDisp.setFont(new java.awt.Font("Monospaced", 0, 20)); // NOI18N
        InpFDDisp.setText(R.getFDString());

        InpRelDisp.setFont(new java.awt.Font("Monospaced", 0, 20)); // NOI18N
        InpRelDisp.setText(R.toString());

        CandidateLabel.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        CandidateLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        CandidateLabel.setText("Candidate Keys :");

        MinCovLabel.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        MinCovLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        MinCovLabel.setText("Minimal Cover :");

        CandidateKeysLabel.setFont(new java.awt.Font("Monospaced", 0, 20)); // NOI18N
        CandidateKeysLabel.setText(R.getCandidateKeysList());

        MinimalCoverLabel.setFont(new java.awt.Font("Monospaced", 0, 20)); // NOI18N
        MinimalCoverLabel.setText(R.getMinimalCoverString());

        xNFLabel.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        xNFLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        xNFLabel.setText("NF :");

        NormalFormLabel.setFont(new java.awt.Font("Monospaced", 0, 20)); // NOI18N
        NormalFormLabel.setText(R.getNormalFormString());

        FDLabel.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        FDLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        FDLabel.setText("FD Table :");

        FDTableDispTextArea.setEditable(false);
        FDTableDispTextArea.setColumns(20);
        FDTableDispTextArea.setFont(new java.awt.Font("Monospaced", 0, 20)); // NOI18N
        FDTableDispTextArea.setRows(5);
        FDTableDispTextArea.setText(R.normalFormsTableGen());
        jScrollPane1.setViewportView(FDTableDispTextArea);

        javax.swing.GroupLayout RelDetailsPanelLayout = new javax.swing.GroupLayout(RelDetailsPanel);
        RelDetailsPanel.setLayout(RelDetailsPanelLayout);
        RelDetailsPanelLayout.setHorizontalGroup(
            RelDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RelDetailsPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(RelDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(MinCovLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CandidateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                    .addComponent(FDLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(xNFLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(RelDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CandidateKeysLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MinimalCoverLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 736, Short.MAX_VALUE)
                    .addComponent(NormalFormLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        RelDetailsPanelLayout.setVerticalGroup(
            RelDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RelDetailsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RelDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CandidateKeysLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CandidateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RelDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(MinCovLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(MinimalCoverLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RelDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RelDetailsPanelLayout.createSequentialGroup()
                        .addComponent(FDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(RelDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(xNFLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(NormalFormLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(34, 34, 34))
        );

        TabbedPane.addTab("Relation Details", RelDetailsPanel);

        FinishButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        FinishButton.setText("FINISH");
        FinishButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinishButtonActionPerformed(evt);
            }
        });

        DecomposedRelLabel.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        DecomposedRelLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        DecomposedRelLabel.setText("Decomposed Relations :");

        DecomposedRelationTextArea.setEditable(false);
        DecomposedRelationTextArea.setColumns(20);
        DecomposedRelationTextArea.setFont(new java.awt.Font("Monospaced", 0, 20)); // NOI18N
        DecomposedRelationTextArea.setRows(5);
        DecomposedRelationTextArea.setText(R.normalizeRelationByOneLevel());
        jScrollPane2.setViewportView(DecomposedRelationTextArea);

        javax.swing.GroupLayout DecomposedTablePanelLayout = new javax.swing.GroupLayout(DecomposedTablePanel);
        DecomposedTablePanel.setLayout(DecomposedTablePanelLayout);
        DecomposedTablePanelLayout.setHorizontalGroup(
            DecomposedTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DecomposedTablePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DecomposedTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(DecomposedTablePanelLayout.createSequentialGroup()
                        .addComponent(DecomposedRelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 732, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DecomposedTablePanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(FinishButton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        DecomposedTablePanelLayout.setVerticalGroup(
            DecomposedTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DecomposedTablePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DecomposedRelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(FinishButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        TabbedPane.addTab("Decomposition Details", DecomposedTablePanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RelPageTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(RelationInputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(InpRelDisp, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(FDInputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(InpFDDisp, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(TabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(RelPageTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(RelationInputLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(InpRelDisp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(FDInputLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(InpFDDisp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(TabbedPane))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FinishButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinishButtonActionPerformed
        // TODO add your handling code here:
        Module1GUI.inputsPage.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_FinishButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RelationDetailsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RelationDetailsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RelationDetailsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RelationDetailsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RelationDetailsPage(R).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CandidateKeysLabel;
    private javax.swing.JLabel CandidateLabel;
    private javax.swing.JLabel DecomposedRelLabel;
    private javax.swing.JTextArea DecomposedRelationTextArea;
    private javax.swing.JPanel DecomposedTablePanel;
    private javax.swing.JLabel FDInputLabel;
    private javax.swing.JLabel FDLabel;
    private javax.swing.JTextArea FDTableDispTextArea;
    private javax.swing.JButton FinishButton;
    private javax.swing.JLabel InpFDDisp;
    private javax.swing.JLabel InpRelDisp;
    private javax.swing.JLabel MinCovLabel;
    private javax.swing.JLabel MinimalCoverLabel;
    private javax.swing.JLabel NormalFormLabel;
    private javax.swing.JPanel RelDetailsPanel;
    private javax.swing.JLabel RelPageTitleLabel;
    private javax.swing.JLabel RelationInputLabel;
    private javax.swing.JTabbedPane TabbedPane;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel xNFLabel;
    // End of variables declaration//GEN-END:variables
}
